### PR TITLE
DNMY: Potential, untested simplifications

### PR DESCRIPTION
**Pull request by odow**
Hey! Cool work. I'll have a think about how to incorporate some of your ideas into SDDP.jl. 

If you haven't already, you might want to take a look at the work @frapac did in https://github.com/JuliaStochOpt/Scenarios.jl

Just a couple of suggestions related to the SDDP.jl stuff showing how you can use JuMP to simplify the models. I haven't tested that I get the same results because I don't have Julia 0.6 on this machine, so you shouldn't merge as-is.

Do you mind if I add all your examples (with credit) to the latest SDDP.jl?

### CODE REVIEW

**Comment by odow** [comment]
See https://github.com/odow/SDDP.jl/pull/209 for a version that has been tested.

**Comment by lingquant** [comment]
You are welcome to use my examples.

**Comment by odow** [comment]
Great! Do you mind commenting on the license implications of using the ONS data?

https://github.com/odow/SDDP.jl/pull/209#issue-278024529

**Comment by odow** [comment]
Closing as stale.

**Pull request closed without merging**
